<?php
/**
 * Plugin Name: Easy Admin CSS
 * Plugin URI: http://www.phpczar.com/blog/
 * Description: The simple, solid way to add custom CSS to your WordPress Admin Area. Easy Admin CSS allows you to add your own styles or override the default CSS of wordpress admin.
 * Author: Praveen Singh Shekhawat | Wordpress King 
 * Author URI: http://www.phpczar.com/
 * Version: 1.0.1
 *
 * Copyright 2014  Praveen Singh Shekhawat (email : shlokjodha@gmail.com)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2, as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * @author Praveen Singh Shekhawat
 * @version 1.0.1
 * */
// Get already exist css
$getCss = getCss();
if (!empty($getCss) && (!file_exists(css_path()))) {
    doCss();
}

function css_path() {
    global $blog_id;
    $cssid = ( $blog_id > "1" ) ? $cssid = "_id-" . $blog_id : $cssid = null;
    $pp = wp_upload_dir();
    $css_path = $pp['basedir'] . "/my_style" . $cssid . ".css";
    return $css_path;
}

function css_url() {
    global $blog_id;
    $cssid = ( $blog_id > "1" ) ? $cssid = "_id-" . $blog_id : $cssid = null;
    $pp = wp_upload_dir();
    $css_url = $pp['baseurl'] . "/my_style" . $cssid . ".css";    
    return $css_url;
}

function icon_link() {
    $icon_link = plugin_dir_url(__FILE__) . "images/css-icon.png";
    return $icon_link;
}

function getCss() {
    // Strip tag for security reason!
    $getCss = strip_tags(get_option('easy_admin_css'));
    return $getCss;
}

function doCss() {
    // make my_style.css and write write css code!
    $result = file_put_contents(css_path(), "/********* Do not edit this file *********/ \n /* \n Easy Admin CSS - Created by Praveen Singh Shekhawat\n  http://www.phpczar.com/ \n */ \n \n" . getCss());
    return $result;
}

// Start Add link on plugins page
function easy_admin_css_links($links) {
    # Settings:
    $settings_link = '<a href="admin.php?page=easy_admin_css" title="Easy Admin CSS">' . __('Settings', 'eacss') . '</a>';
    array_unshift($links, $settings_link);
    # Support:
    $support_forum = '<a href="http://www.phpczar.com/" title="PHPCzar">' . __('Support', 'eacss') . '</a>';
    array_unshift($links, $support_forum);
    # return:
    return $links;
}

function add_plugin_meta_links($links, $file) {
    if ($file == plugin_basename(__FILE__)) {
        $links[] = '<a href="http://www.phpczar.com/" title="Buy Me a Pizza ;)">Donate :)</a>';
    }
    return $links;
}

// End Add link on plugins page
// Change the CSS for this plugin on admin plugins page

function eacss_admin() {
    $plugin_page = add_menu_page(__('Easy Admin CSS Panel', 'eacss'), __('Easy Admin CSS', 'eacss'), 'manage_options', 'easy_admin_css', 'eacss_options', icon_link(), 61);
    add_action('admin_init', 'register_settings_eacss');

    add_action('admin_head-' . $plugin_page, 'eacss_syntax');

    // Disable "WP Editor" in this page if is active: http://wordpress.org/extend/plugins/wp-editor/
    If (is_plugin_active("wp-editor/wpeditor.php") && $_SERVER['QUERY_STRING'] == 'page=easy_admin_css') {

        function remove_wpeditor_header_info() {
            // Wp Editor Script
            wp_deregister_script('wpeditor');
            wp_deregister_script('wp-editor-posts-jquery');
            wp_deregister_script('fancybox');
            wp_deregister_script('codemirror');
            wp_deregister_script('codemirror_php');
            wp_deregister_script('codemirror_javascript');
            wp_deregister_script('codemirror_css');
            wp_deregister_script('codemirror_xml');
            wp_deregister_script('codemirror_clike');
            wp_deregister_script('codemirror_dialog');
            wp_deregister_script('codemirror_search');
            wp_deregister_script('codemirror_searchcursor');
            wp_deregister_script('codemirror_mustache');
            // Wp Editor Style
            wp_deregister_style('wpeditor');
            wp_deregister_style('fancybox');
            wp_deregister_style('codemirror');
            wp_deregister_style('codemirror_dialog');
            wp_deregister_style('codemirror_themes');
        }

        // Deregister Already exist CSS and Scripts
        add_action('admin_init', 'remove_wpeditor_header_info', 20);
    }
}

function eacss_syntax() {
    $plugdir = plugin_dir_url(__FILE__);

    echo '<link type="text/css" rel="stylesheet" href="' . $plugdir . 'lib/codemirror.css" />';

    echo '<script language="javascript" src="' . $plugdir . 'lib/codemirror.js"></script>';
    echo '<script language="javascript" src="' . $plugdir . 'lib/css.js"></script>';
}

// Register Settings
function register_settings_eacss() {
    register_setting('eacss_settings', 'easy_admin_css');
}

function eacss_options() {
    ?>
    <div class="wrap">
        <h2><?php _e('Easy Admin CSS Options', 'eacss'); ?></h2>
        <form method="post" action="options.php">
            <?php settings_fields('eacss_settings'); ?>
            <p><?php _e('Custom CSS Code:', 'eacss'); ?></p>
            <textarea name="easy_admin_css" id="easy_admin_css" dir="ltr" style="width:100%;height:350px;"><?php echo get_option('easy_admin_css'); ?></textarea>
            <script language="javascript">
                var editor = CodeMirror.fromTextArea(document.getElementById("easy_admin_css"), {lineNumbers: true});
            </script>
            <p>
                <input type="submit" class="button-primary" value="<?php _e('Save', 'eacss'); ?>" />
                <input type="button" class="topArrow" value="^" onclick="self.scrollTo(0, 0); return false;"/>
            </p>
        </form>
    </div>
    <?php
    // Save also in *.css file!
    $getCss = getCss();
    if (!empty($getCss)) {
        doCss();
    } elseif (empty($getCss) && file_exists(css_path())) {
        unlink(css_path());
    }
}

function add_my_css(){
    if (file_exists(css_path())) {
        echo '<link type="text/css" rel="stylesheet" href="' . css_url() . '" />';
    }
}
add_action('admin_menu', 'eacss_admin');
add_filter('plugin_row_meta', 'add_plugin_meta_links', 10, 2);
add_filter('plugin_action_links_' . plugin_basename(__FILE__) . '', 'easy_admin_css_links');

// Add My CSS in admin footer
add_action('admin_footer', 'add_my_css');
?>